name: 01-Building_Blocks
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World!"
    echo-goodbuy:
        runs-on: ubuntu-latest
        steps:
            - name: Successfull step
              run: |
                echo "I will succeed"
                exit 0
            - name: say Goodbye
              run: echo "Goodbye!!"
