name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        description: Build status to simulate
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1}}
    steps:
      - name: Print GITHUB_OTPUT path
        run: echo "GITHUB_OUTPUT is $GITHUB_OUTPUT"
      
      - name: Build
        id: build
        run: |
          echo "status=${{ inputs.build-status }} >> $GITHUB_OUTPUT"
          echo "output1=value1" >> $GITHUB_OUTPUT

      - name: Step with mistake
        run: |
          echo "output2=value2" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          echo "mistake=true" > $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying"

      - name: Print Outputs
        run: |
          echo "Output1 from build job is: ${{ needs.build.outputs.output1 }}"



  